[package]
name = "webapp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web="4.8.0"
dotenv="0.15.0"
serde = {version = "1.0.203",features=["derive"]}
awc = "3.5.0"
serde_json = "1.0.120"
tera = "1.20.0"
uuid = { version = "1.9.1", features = ["v4", "serde"] }